### ISSUE TITLE
FontAwesome icon not shown when using CDN variant

### ISSUE THREAD

**Issue by bbfriend** [cmb69/fa_xh#28]
When using CDN version of TinyMCE, `tinymce.baseURL` becomes CDN(ex.http://cdnjs.cloudflare.com/...)
If use fontawesome/fontawesome.png
Now(1.0rc2)
```
    editor.addButton('fontawesome', {
        image: tinymce.baseURL + '/../../fa/editors/tinymce4/fontawesome/fontawesome.png',
```
to
```
    editor.addButton('fontawesome', {
//        image: tinymce.baseURL + '/../../fa/editors/tinymce4/fontawesome/fontawesome.png',
        image: url + '/fontawesome.png',
```
and
```
    editor.addMenuItem('fontawesome', {
        image: tinymce.baseURL + '/../../fa/editors/tinymce4/fontawesome/fontawesome.png',
```
to
```
    editor.addMenuItem('fontawesome', {
//        image: tinymce.baseURL + '/../../fa/editors/tinymce4/fontawesome/fontawesome.png',
        image: url + '/fontawesome.png',
```

But, already have web fonts, so do not use `fontawesome.png` I think that the following is good.
 ```
   editor.addButton('fontawesome', {
        icon: 'fort-awesome',
        tooltip: 'Font Awesome', // or translate('Font Awesome') ,and Add/Edit lang/*.js
        onclick: showDialog 
    });

    editor.addMenuItem('fontawesome', {
        icon: 'fort-awesome',
        text: 'Font Awesome', //or translate('Font Awesome') ,and Add/Edit lang/*.js
        onclick: showDialog,
        context: 'insert'
    });
```
and Add to editors/tinymce4/fontawesome/css/fontawesome.min.css

`.mce-i-fort-awesome{font-family:FontAwesome !important;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;font-size:15px}.mce-i-fort-awesome:before{content:"\f286"}`

Considering the future,
 I think that it is good to keep the code of[ josh18](https://github.com/josh18/TinyMCE-FontAwesome-Plugin).
```
    editor.addButton('fontawesome', {
        icon: 'flag',
        text: translate('Icons'),
        tooltip: translate('Icons'),
        onclick: showDialog
    });

    editor.addMenuItem('fontawesome', {
        icon: 'flag',
        text: translate('Icons'),
        onclick: showDialog,
        context: 'insert'
});
```
:sweat: I am sorry that I am not good at English.

**Comment by cmb69** [comment]
Thanks! The usage of `tinyMCE.baseURL` is obviously wrong.

I'm not sure whether it is a good idea to add a CSS class to the mce namespace (`.mce-i-fort-awesome`) for forward compatibility. Is that part of the official TinyMCE documentation? Otherwise it looks like a hack to me.

Regarding compatibility with the original FA plugin: it seems to me that its development has basically discontinued, and I already had made a few adjustments and updated to Font Awesome 4.7, so if there'll be any updates to the original plugin, I'd likely have to cherry-pick new commits anyway.
